---
title: Developer Note
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
tagline: because my memory has limit...
email: your-email@domain.com
description: 'I’m a sofware engineer from Indonesia. Currently I’m working as software
  engineer at KMKLabs. Develop software in an Agile way, using Extreme Programming
  methodologies (pair programming, test driven development, continuous integration,
  and continuous deployment)

'
baseurl: ''
url: https://blog.wilianto.com
permalink: "/:title.html"
twitter_username: jekyllrb
github_username: jekyll
disqus:
  shortname: https-blog-wilianto-com
google_analytics: UA-11774853-5
markdown: kramdown
theme: jekyll-theme-putih-bersih
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
