---
title: Developer Note
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  tools:
    title: Tools
    output: true
  uploads:
    title: Uploads
    output: true
tagline: because my memory has limit...
email: your-email@domain.com
description: 'Personal blog for my learning, working and sharing note about tech.'
baseurl: ''
url: https://blog.wilianto.com
permalink: "/:title.html"
twitter_username: jekyllrb
github_username: jekyll
disqus:
  shortname: https-blog-wilianto-com
google_analytics: UA-11774853-5
markdown: kramdown
theme: jekyll-theme-cayman
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
